version: '3.8'

services:
  war_room_dashboard:
    build: .
    container_name: c5i_dashboard
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - 'C:\PROGRAMA\Evidencias_IG:/app/Evidencias_IG'
      - 'C:\PROGRAMA\Evidencias_IG:/app/evidencias'
      - './ig_session:/tmp/.instaloader-root'
    restart: always

  motor_rss:
    build: .
    container_name: c5i_motor_rss
    command: python -u motor_24_7v2.py
    volumes:
      - 'C:\PROGRAMA\Evidencias_IG:/app/evidencias'
    extra_hosts:
      - "localhost:host-gateway"
    restart: always

  cazador_ig:
    build: .
    container_name: c5i_cazador_ig
    command: python -u cazador_igv2.py
    volumes:
      - 'C:\PROGRAMA\Evidencias_IG:/app/Evidencias_IG'
      - './ig_session:/root/.config/instaloader'
    extra_hosts:
      - "localhost:host-gateway"
    restart: always